Download NY Head model files automatically if missing
LFPy/LFPykit pull request #192
Opened 2023-04-11 08:40 UTC by torbjone

Switch to automatic downloading of New York Head model, if file location is not given.

Closes #193

2023-04-11 11:37 UTC, espenhgn requested changes

2023-04-11 13:49 UTC, espenhgn reviewed
Can you also bump the version number in `LFPykit/version.py` to 0.5.1?

2023-04-12 06:51 UTC, torbjone commented
Does it look good now?

2023-04-12 06:55 UTC, espenhgn approved these changes
Excellent!

2023-04-12 06:55 UTC, merged